version: '3.1'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    restart: always

  frontend:
    build: ./frontend
    ports:
      - "7777:80"
    environment:
      - VITE_API_URL=http://backend:5000
    restart: always
