apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: samitenthouse
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      name: backend
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: monusiddiki/samitenthouse-backend:v3
          envFrom:
            - secretRef:
                name: backend-env
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: samitenthouse
spec:
  type: NodePort
  selector:
    app: backend
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
      nodePort: 31100 # This is the port exposed on your localhost